### ISSUE TITLE
allow config to work with local dev database

### ISSUE THREAD

**Issue by MrSkinny** [jcloutz/coffee-and-code#3]
Db is currently accessing Mongolabs (requires contribs to have the dev credentials in a secrets.json).  Config file should allow local mongo installation

**Comment by jcloutz** [comment]
That would be great. Maybe add installation instructions to the readme to set up a local environment as well.

**Comment by MrSkinny** [comment]
done 4ff14781ed543fd26e480ea65d0b0a44f3243610
